openapi: 3.1.0
info:
  title: "Colo Inventory API"
  version: 0.0.1
  license:
    name: HPE License
    url: https://www.hpe.com/us/en/software/licensing.html
paths:
  /providers:
    get:
      summary: Lists providers
      description: Lists providers with filtered by query strings.
      responses:
        200:
          description: List of providers
          content:
            application/json:
              schema:
                $ref: "schemas/provider.yaml#/components/schemas/providers"
          links:
            # GET /providers/{providerId}
            GetProviderById:
              description: Return a link to query the provider by id
              operationId: getProviderById
              parameters:
                regionId: $response.body#/providerId
    post:
      summary: Create a new provider
      description: Creates a new provider entity and returns the object.
      operationId: post-providers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
  /providers/{providerID}:
    get:
      summary: List provider by id
      description: List a provider by id
      operationId: getProviderById
      parameters:
        - $ref: "parameters/all.yaml#/components/parameters/providerId"
      responses:
        200:
          description: List provider
          content:
            application/json:
              schema:
                $ref: "schemas/provider.yaml#/components/schemas/providerA"
    put:
      summary: List provider by id
      description: List a provider by id
    delete:
      summary: List provider by id
      description: List a provider by id
  /regions:
    get:
      summary: List all locations for a specific provier
      description: List all locations for a specific provider
      responses:
        200:
          description: List all regions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "schemas/region.yaml#/components/schemas/regionGetObject"
    post:
      summary: List all locations for a specific provier
      description: List all locations for a specific provider
      requestBody:
        content:
          application/json:
            schema:
              $ref: "schemas/region.yaml#/components/schemas/regionPostRequestBody"
      responses:
        201:
          description: Create a new region
          content:
            application/json:
              schema:
                type: object
                properties:
                  regionId:
                    $ref: "schemas/region.yaml#/components/schemas/regionId"
          links:
            # GET /regions/{regionId}
            GetRegionByRegionId:
              description: Return a link to query the region by id
              operationId: getRegionById
              parameters:
                regionId: $response.body#/regionId
  /regions/{regionId}:
    get:
      summary: List location by id for a specific provider
      description: List all locations for a specific provider
      operationId: getRegionById
      parameters:
        - $ref: "parameters/all.yaml#/components/parameters/regionId"
      responses:
        200:
          description: Return info for the specified regionId
          content:
            application/json:
              schema:
                $ref: "schemas/region.yaml#/components/schemas/regionGetObject"
    put:
      summary: List location by id for a specific provider
      description: List all locations for a specific provider
    delete:
      summary: List location by id for a specific provider
      description: List all locations for a specific provider
  /regions/{regionId}/zones:
    get:
      summary: List all locations for a specific provier
      description: List all locations for a specific provider
      responses:
        200:
          description: Return list of zones for specificed regionId
          content:
            application/json:
              schema:
                $ref: "schemas/zone.yaml#/components/schemas/zonesListObject"
    post:
      summary: List all locations for a specific provier
      description: List all locations for a specific provider
      requestBody:
        content:
          application/json:
            schema:
              $ref: "schemas/zone.yaml#/components/schemas/zonePostRequestBody"
      responses:
        201:
          description: Create a new zone within a sepcified region
          content:
            application/json:
              schema:
                type: object
                properties:
                  zoneId:
                    $ref: "schemas/zone.yaml#/components/schemas/zoneId"
          links:
            # GET /zones/{zoneId}
            GetZoneByZoneId:
              description: Return a link to query the zone by zoneId
              operationId: getZoneById
              parameters:
                zoneId: $response.body#/zoneId
  /zones/{zoneId}:
    get:
      summary: List location by id for a specific provider
      description: List all locations for a specific provider
      operationId: getZoneById
      parameters:
        - name: zoneId
          in: path
          required: true
          description: UUID of the Zone
          schema:
            $ref: "schemas/zone.yaml#/components/schemas/zoneId"
      responses:
        200:
          description: Return info for the specified regionId
          content:
            application/json:
              schema:
                $ref: "schemas/zone.yaml#/components/schemas/zoneGetObject"
    put:
      summary: List location by id for a specific provider
      description: List all locations for a specific provider
    delete:
      summary: List location by id for a specific provider
      description: List all locations for a specific provider
  /zones/{zoneId}/deployments:
    get:
      summary: List location by id for a specific provider
      description: List all locations for a specific provider
    post:
      summary: List all locations for a specific provier
      description: List all locations for a specific provider
  /deployments/{deploymentId}:
    get:
      summary: List location by id for a specific provider
      description: List all locations for a specific provider
      responses:
        200:
          description: Return a deployment by deploymentId
          content:
            application/json:
              schema:
                $ref: "schemas/deployment.yaml#/components/schemas/deploymentGetObject"
    put:
      summary: List location by id for a specific provider
      description: List all locations for a specific provider
    delete:
      summary: List location by id for a specific provider
      description: List all locations for a specific provider
  /cabinets/{cabinetId}:
    get:
      summary: Return cabinet information for cabinetId
      description: List all locations for a specific provider
      operationId: getCabinetById
      parameters:
        - name: cabinetId
          in: path
          required: true
          description: UUID of the Cabinet
          schema:
            $ref: "schemas/cabinet.yaml#/components/schemas/cabinetId"
      responses:
        200:
          description: Return the specified cabinet object
          content:
            application/json:
              schema:
                $ref: "schemas/cabinet.yaml#/components/schemas/cabinetGetObject"
    post:
      summary: List all locations for a specific provier
      description: List all locations for a specific provider
components:
  schemas:
